from abc import ABC, abstractmethod
from ..entities import Job, ThreeDModel
class AbstractJobRepository(ABC):
    @abstractmethod
    async def save(self, job: Job) -> None: ...
    @abstractmethod
    async def get_by_id(self, job_id: str) -> Job | None: ...
class AbstractModelRepository(ABC):
    @abstractmethod
    async def save(self, model: ThreeDModel) -> None: ...
    @abstractmethod
    async def get_by_job_id(self, job_id: str) -> ThreeDModel | None: ...